name: "branch deploy demo"

# The workflow will execute on new comments on pull requests - example: ".deploy" as a comment
on:
  issue_comment:
    types: [created]

# Permissions needed for reacting and adding comments for IssueOps commands
permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read
  statuses: read

jobs:
  demo:
    if: ${{ github.event.issue.pull_request }} # only run on pull request comments (no need to run on issue comments)
    runs-on: ubuntu-latest
    steps:
      # Execute IssueOps branch deployment logic, hooray!
      # This will be used to "gate" all future steps below and conditionally trigger steps/deployments
      - uses: github/branch-deploy@v10.0.0
        id: branch-deploy # it is critical you have an id here so you can reference the outputs of this step
        with:
          environment: stable
          environment_targets: alpha,beta,stable
          enforced_deployment_order: alpha,beta,stable

      # Run your deployment logic for your project here - examples seen below


      # Do some fake "noop" deployment logic here
      # conditionally run a noop deployment
      - name: fake noop deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop == 'true' }} # only run if the trigger phrase is found and the branch-deploy step detected a noop deployment
        run: echo "I am doing a fake noop deploy of commit ref ${{ steps.branch-deploy.outputs.ref }} to environment ${{ steps.branch-deploy.outputs.environment }}"
      # Checkout your project repository based on the ref provided by the branch-deploy step
      - uses: actions/checkout@v4.2.2
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' }} # only run if the trigger phrase is found and the branch-deploy step detected a regular deployment
        with:
          ref: ${{ steps.branch-deploy.outputs.environment }} # uses the detected branch from the branch-deploy step
      # Do some fake "regular" deployment logic here
      # conditionally run a regular deployment
      - name: regular deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' }} # only run if the trigger phrase is found and the branch-deploy step detected a regular deployment
        run: |
          git merge --no-ff --no-edit ${{ steps.branch-deploy.outputs.ref }}
